version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db postgres
    db:
        image: postgres:15.5-alpine3.18
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE:-laravel}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-userpass}
            POSTGRES_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgres
        ports:
            - "5432:5432"
        networks:
            - laravel

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
